sonar.projectKey=Makoper-PixelForge
sonar.projectName=Makoper PixelForge
sonar.projectVersion=1.0

sonar.sources=backend/src,frontend/src,game/src
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/__pycache__/**,**/*.pyc,**/node_modules/**,**/dist/**,**/.venv/**,security-reports/**,database/**,infra/**